### ISSUE TITLE
Bug when training perfusion

### ISSUE THREAD

**Issue by tuanh123789** [irowberry/perfusion-training#1]
Thank for your amazing work. I have a problem when run script train_perfusion.py
`RuntimeError: The expanded size of the tensor (4096) must match the existing size (4173) at non-singleton dimension 2.  Target sizes: [16, 4096, 4096].  Tensor sizes: [16, 1, 4173]`.
What version diffusers do you using?

**Comment by irowberry** [comment]
If you look at the ReadMe I explain that there's a TODO in the latest version of diffusers, I recommend cloning diffusers, then installing it with `pip install -e diffusers/`. After, navigate to `diffusers/models/attention_processor.py` within that file there is a function called `prepare_attention_mask` There's an if branch that is currently
```
 if current_length != target_length:
            if attention_mask.device.type == "mps":
                # HACK: MPS: Does not support padding by greater than dimension of input tensor.
                # Instead, we can manually construct the padding tensor.
                padding_shape = (attention_mask.shape[0], attention_mask.shape[1], target_length)
                padding = torch.zeros(padding_shape, dtype=attention_mask.dtype, device=attention_mask.device)
                attention_mask = torch.cat([attention_mask, padding], dim=2)
            else:
                # TODO: for pipelines such as stable-diffusion, padding cross-attn mask:
                #       we want to instead pad by (0, remaining_length), where remaining_length is:
                #       remaining_length: int = target_length - current_length
                # TODO: re-enable tests/models/test_models_unet_2d_condition.py#test_model_xattn_padding
                attention_mask = F.pad(attention_mask, (0, target_length), value=0.0)
```
You have to change the last line to this `attention_mask = F.pad(attention_mask, (0, target_length - current_length), value=0.0)` and it will fix that issue.
